travis:
  secure:
    BINSTAR_TOKEN: Rm2vBm0sXS9uajtMOTck/kAPALX2TrZG5NQk53jRLeJmr54Njg2LjoHkoQLvfPc0eMQXs9gVududZfKiMVPf/RT9YLkoFjZNZhoseVQHQkkRNk9cjqjH87Y1JbkHPsZMcbOM2SvriYjRALZusS6ONSy0lT8rihQo+cNQYhb/ViWf7YcTekkgYfkjLl+SB0W5PwnNaJ2EsHtUKqyPH1+dgELeV1A8JmcTK1uvOfAc9yZAYv9cEf6+6jLoFU+HmR8py2ZiONkAg1rnnjUa+wLXHNgkHRIq0gaGqc4393B0E2pbeZckG7ng7tQ0VtDk1FyEo6oToPLEXtaSDzG2ej4jhtX71R+WgaBu9fyzoOzpDGQuNxY2RVtMacXaJmU8UNlXA0sjsfMQWvB40YU9Pk/hOcbUPy9NdgSsRYYfij/Ty4c1nRZBFHlTbWyDt3rBv+0QQMsYgiFWVo0L+tKSg2zP3coMYNnb9mfnbMfywnV8BJoF/okSa0IfwgTOBuxl9fELc05f6KRZ1/RLmkQo03Z+jLrZg7IQBJhvWWiJrFK8rmm9JSMBR6mK+Oe9K8s2hjWnL5jqP+zx8T0yKWWdBLwUdytTcllpltb2fh6f0/b8H69ZX/dWJk918TUVX3SF1HdayfkBs2WkUPq64KqJ30pF01pfixh28R9ak9XaY8VlZC8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
